CREATE TABLE [dbo].[Utilisateur]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[Email] NVARCHAR(250) NOT NULL,
	[Pwd] NVARCHAR(250) NOT NULL,
	[Role] VARCHAR(50) NOT NULL, 
    CONSTRAINT UK_Utilisateur_Email UNIQUE (Email)
)
